name: interview_task_vasai
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  curved_navigation_bar: ^1.0.6  
  google_fonts: ^6.2.1
  weekly_date_picker: ^1.4.2
  intl: ^0.20.2
  fl_chart: ^0.71.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: DM Sans
      fonts:
        - asset: assets/fonts/DMSans_18pt-Light.ttf
          weight: 400
        - asset: assets/fonts/DMSans_18pt-Medium.ttf
          weight: 600
        - asset: assets/fonts/DMSans_24pt-Bold.ttf
          weight: 700  
